app:
  port: 3000
  globalPrefix: 'api'
  NODE_ENV: development

logger:
  colorize: true
  defaultLevel: info
  prettyLogs: true

cors:
  enabled: true
  origin:
    - 'http://localhost:3000'
    - 'http://localhost:3001'
  methods: 'GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS'
  preflight_continue: false
  options_success_status: 204
  credentials: true
  max_age: 3600

throttler:
  enabled: true
  ttl: 60000
  limit: 10
  errorMessage: 'Too many requests, please try again later.'

swagger:
  enable: true
  path: 'doc'

database:
  user: postgres
  password: postgres
  host: localhost
  port: 5438
  name: aiofc_db

redis:
  mode: standalone # 可选值: 'standalone', 'cluster', 'sentinel'
  standalone:
    host: localhost
    port: 26379
    password: '123456'
    db: 5
  cluster:
    - host: '127.0.0.1'
      port: 7000
      password: ''
    - host: '127.0.0.1'
      port: 7001
  sentinel:
    sentinels:
      - host: '127.0.0.1'
        port: 26379
      - host: '127.0.0.1'
        port: 26380
    name: master
    password: ''
    db: 5
